//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminTemp.Areas.GstBill.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceDetail
    {
        public int IId { get; set; }
        public string INo { get; set; }
        public string IDraftNo { get; set; }
        public Nullable<System.DateTime> IDate { get; set; }
        public int ICustId { get; set; }
        public string IinvoiceStatus { get; set; }
        public decimal TotalValue { get; set; }
        public decimal TotalGST { get; set; }
        public decimal TotalTotal { get; set; }
        public decimal GrandTotal { get; set; }
        public string INotes { get; set; }
        public string IDONumber { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool IsActive { get; set; }
    }
}
