//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminTemp.Areas.GstBill.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemTransaction
    {
        public int IdT { get; set; }
        public string InvoiceNoT { get; set; }
        public string DraftNoT { get; set; }
        public string ItemCodeT { get; set; }
        public string ItemDetails { get; set; }
        public string ItemmPart { get; set; }
        public string HSN { get; set; }
        public Nullable<int> Quantity { get; set; }
        public decimal Rate { get; set; }
        public decimal Value { get; set; }
        public decimal GstRate { get; set; }
        public decimal GstValue { get; set; }
        public decimal Total { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool IsActive { get; set; }
    }
}
