//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdminTemp.Areas.GstBill.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemMaster
    {
        public int ItemId { get; set; }
        public string ItemCode { get; set; }
        public string ItemDetails { get; set; }
        public string ItemPart { get; set; }
        public string HSN { get; set; }
        public Nullable<decimal> Rate { get; set; }
        public int Gst { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public bool IsActive { get; set; }
    }
}
